version: 2.1

jobs:
  deploy_linux:
    parameters:
      label:
        type: string
        default: main
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - run:
          name: Install conda-build/anaconda-client
          command: |
            conda install -y -q conda-build anaconda-client
            conda config --set anaconda_upload yes
            anaconda auth -i
      - run:
          name: Build packages
          command: |
            cd conda
            # conda build faiss --user pytorch --label <<parameters.label>>

workflows:
  version: 2
  build:
    jobs:
      - deploy_linux:
          name: Linux packages
